version: '3.8'
services:
    postgres:
        image: postgres:12.9
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
            options:
              max-size: 10m
              max-file: "3"
        ports:
            - '5432:5432'
        volumes:
            - ./volumes/postgres-data:/var/lib/postgresql/data
            # copy the sql script to create tables
            - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/init.sql
    gin:
        build:
            context: ./
            dockerfile: Dockerfile
            labels:
                - gin
        ports:
            - "8080:8080"
        depends_on:
            - postgres
